language: php
php:
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

before_script:
  - composer self-update

install:
  - composer install
  - ls
  
script:
  - phpunit --bootstrap tests/bootstrap.php testRoutes tests/Route/RouteTest.php
