language: php
php:
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

install:
  - composer self-update
  - composer install --prefer-source
  
script:
  - phpunit --bootstrap tests/bootstrap.php testRoutes tests/Route/RouteTest.php
